name: Download Files Monthly

on:
  schedule:
    - cron: '0 0 1,2,3,4,5 * *'
    
jobs:
  run-script:
    runs-on: ubuntu-lateste
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'
    
      - name: Install dependencies
        run: pip install -r requirements.txt
    
      - name : Run script
        run: python ../src/main.py
